### ISSUE TITLE
tko_web_sessions_management - 500: Internal Server Error

### ISSUE THREAD

**Issue by axatech01** [thinkopensolutions/tkobr-addons#297]
Error issued after installing module and then re-start odoo service, steps followed:

1- Initiate server
2- Access Odoo host with Admin user.
3- Enable the Developer Mode.
4- Install the tko_web_sessions_management  and try to setup module by defining the policy on Employees' group,
5- Try to test different settings: 1 Hour limit session, No multiple login, etc....
6- Restart Odoo service.
7- Try again to test the module, but could not access to http://localhost, this is what Linux log show up:

 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/website/controllers/main.py", line 84, in web_login
    if not redirect and request.params['login_success']:
KeyError: 'login_success'

**Key Facts**:
- Find that tko_web_sessions_management  failed with No multiple login.
- After re-starting the Odoo service can not access to 
http://localhost/web/login, with message _**500: Internal Server Error**_
- There is not feature on company form to setup Odoo Company wise settings for tko_web_sessions_management, it exists only for user's Groups.

Thanks for sharing your module, it is great!!.

**Comment by cmsalmeida** [comment]
Hi thank you for your issue.
Can you tell me what Odoo version you are testing with?
Make sure you match versions.
Let me know if you still have issues with it, we merged a fix yesterday in v10.0

**Comment by axatech01** [comment]
Hi @cmsalmeida ,
I am using V10.0. I Will test new fix and report back.

**Comment by cmsalmeida** [comment]
Thank you for your message.
We did a new merge with some persistent bug fixes, and some enhancements.
Please let us know if you found more.
