### ISSUE TITLE
NameError: global name 'email' is not defined

### ISSUE THREAD

**Issue by OdreyPapin** [thinkopensolutions/tkobr-addons#351]
Hello, how i can fix this issue ?

```

2017-05-23 09:46:46,383 548 ERROR XXXXX odoo.addons.mail.models.mail_mail: failed sending mail (id: 642) due to global name 'email' is not defined
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/mail/models/mail_mail.py", line 277, in send
    res = IrMailServer.send_email(msg, mail_server_id=mail.mail_server_id.id)
  File "/odoo/custom/addons/tko_mail_smtp_per_user/models/mail_mail.py", line 26, in send_email
    from_rfc2822 = extract_rfc2822_addresses(message['From'])[-1]
`NameError: global name 'email' is not defined`
```

**Comment by cmsalmeida** [comment]
Hi,
Thank you for your issue.
Can you give us more info about that error?
Have you tried to update the module?
