### ISSUE TITLE
about session manager some error

### ISSUE THREAD

**Issue by lonelyleaves** [thinkopensolutions/tkobr-addons#383]
My odoo version is 10, using this module, when installed, there will be error messages: 

  File "/opt/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 6:                                AND gu.uid = false
                                                  ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
2017-05-27 06:46:52,574 1181 WARNING cvk odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.

and Log has a lot of wrong information 
2017-05-27 07:54:23,419 10851 WARNING cvk odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.

and menu xml is not normal 

Session Timeout be next to Login Calendar

**Comment by cmsalmeida** [comment]
Thank you for your issue.
This was already fixed.
Please let us know if you found more.

**Comment by lonelyleaves** [comment]
have one problem when haved user two day 

2017-06-09 10:34:23,332 28380 INFO lots werkzeug: 127.0.0.1 - - [09/Jun/2017 10:34:23] "GET /web/database/manager HTTP/1.1" 403 -
2017-06-09 10:35:06,299 28380 INFO lots odoo.sql_db: ConnectionPool(used=1/count=3/max=64): Free leaked connection to 'dbname=lots user=openerp password=xxxxxxx host=127.0.0.1 port=65432'
2017-06-09 10:35:06,734 28380 INFO lots odoo.sql_db: bad query: UPDATE ir_sessions SET date_expiration='2017-06-16 10:35:06', session_duration='2 days, 21:54:51' WHERE id= 1
2017-06-09 10:35:06,734 28380 INFO lots odoo.addons.base.ir.ir_http: Exception during request Authentication.
Traceback (most recent call last):
  File "D:\Odoo\odoo10\odoo\addons\base\ir\ir_http.py", line 103, in _authenticate
    request.session.check_security()
  File "D:\Odoo\odoo10\odoo\http.py", line 1056, in check_security
    security.check(self.db, self.uid, self.password)
  File "D:\Odoo\odoo10\odoo\service\security.py", line 13, in check
    return res_users.check(db, uid, passwd)
  File "E:\Odoo\Odoo\myaddons10\tko_web_sessions_management\res_users.py", line 88, in check
    self.browse(uid)._check_session_validity(db, uid, passwd)
  File "E:\Odoo\Odoo\myaddons10\tko_web_sessions_management\res_users.py", line 74, in _check_session_validity
    session_id.id,))
  File "D:\Odoo\odoo10\odoo\sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Odoo\odoo10\odoo\sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
DataError: value too long for type character varying(8)

2017-06-09 10:35:06,736 28380 WARNING lots odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.
