### ISSUE TITLE
tko_web_sessions_management  - access right

### ISSUE THREAD

**Issue by mhabou** [thinkopensolutions/tkobr-addons#7]
Hi everyone,

Thx for this nice work,

i got the error bellow when i tried to log in with demo user (with admin user there is no problem)

2015-11-01 18:39:24,080 13995 ERROR 7000DemoSession werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/home/inovativ/workspace/odoo8/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 1290, in **call**
    return self.dispatch(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 1264, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 1264, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 1435, in dispatch
    result = ir_http._dispatch()
  File "/home/inovativ/workspace/odoo8/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/home/inovativ/workspace/odoo8/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/inovativ/workspace/odoo8/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 684, in dispatch
    r = self._call_function(*_self.params)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/inovativ/workspace/odoo8/custom/telecom/tko_web_sessions_management/main.py", line 88, in web_login
    context=None)
  File "/home/inovativ/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/models.py", line 1644, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/inovativ/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/models.py", line 4655, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/home/inovativ/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/models.py", line 3502, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/home/inovativ/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in check

  File "/home/inovativ/workspace/odoo8/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Sorry, you are not allowed to access this document. Please contact your system administrator if you think this is an error.\n\n(Document model: ir.sessions)')

**Comment by cmsalmeida** [comment]
Hi,
Can you give more contextual information, I've created a new database, created a demo user, only default values (name demo, login demo, pwd demo):
1- Found a bug, because user didn't had timezone, fixed by d7f9346, and was able to login.
No other errors found.
I've also reviewed security file, no clues.

**Comment by mhabou** [comment]
I think the problem was from an other module.

NB :+1: for me the context contains only the language argument

**Comment by cmsalmeida** [comment]
Great.
I don't understand the "for me the context contains only the language argument" :)

**Comment by mhabou** [comment]
the context shows only the language attribute

**Comment by cmsalmeida** [comment]
ok, I'll close this issue then :)

**Comment by mhabou** [comment]
Thank you for your help
