### ISSUE TITLE
login failed after install

### ISSUE THREAD

**Issue by garzadekoster** [thinkopensolutions/tkobr-addons#99]
Good evening I detected a failure when you install (either in a working instance o a new one)
The trace says a free leaked connection and after tat you can not load the db.
(I updated yesterday) I had this issued (I did install GeoIP) following http://thelinuxfaq.com/360-how-to-install-and-use-geoip-on-fedora-centos-ubuntu

I rolled back to use the version that used to work.  
I would say from this point may be related with some bug on the app.
Hope you have some time to fix this awesome app.   If you need further testing drop me a line.
Best regards Humberto @ mexico

the trace:
016-08-22 14:47:51,439 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:51] "GET /web/login HTTP/1.1" 200 -
2016-08-22 14:47:51,688 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:51] "GET /im_livechat/loader/DHARMAUTIL/1 HTTP/1.1" 200 -
2016-08-22 14:47:51,944 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:51] "POST /web/proxy/load HTTP/1.1" 200 -
2016-08-22 14:47:51,947 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:51] "POST /web/proxy/load HTTP/1.1" 200 -
2016-08-22 14:47:52,229 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:52] "POST /im_livechat/available HTTP/1.1" 200 -
2016-08-22 14:47:55,705 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:55] "GET /web/login HTTP/1.1" 200 -
2016-08-22 14:47:55,877 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:55] "GET /web/login HTTP/1.1" 200 -
2016-08-22 14:47:56,402 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:47:56] "GET /im_livechat/loader/DHARMAUTIL/1 HTTP/1.1" 200 -
2016-08-22 14:48:03,725 1204 ERROR DHARMAUTIL openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 673, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/openerp/http.py", line 691, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/auth_oauth/controllers/main.py", line 93, in web_login
    response = super(OAuthLogin, self).web_login(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/auth_signup/controllers/main.py", line 38, in web_login
    response = super(AuthSignupHome, self).web_login(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/custom/addons/tko_web_sessions_management/main.py", line 154, in web_login
    context=request.context)
  File "/opt/odoo/custom/addons/tko_web_sessions_management/main.py", line 189, in save_session
    if request.httprequest.headers.environ['HTTP_X_FORWARDED_FOR']:
KeyError: 'HTTP_X_FORWARDED_FOR'

2016-08-22 14:48:03,816 1204 WARNING DHARMAUTIL openerp.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.
2016-08-22 14:48:03,820 1204 INFO DHARMAUTIL werkzeug: 189.219.123.100 - - [22/Aug/2016 14:48:03] "POST /web/login HTTP/1.1" 500 -
2016-08-22 14:48:11,391 1204 WARNING DHARMAUTIL openerp.sql_db: ConnectionPool(used=1/count=5/max=64): Free leaked connection to 'user=odoo dbname=DHARMAUTIL'

**Comment by cmsalmeida** [comment]
Fixed in mean time.
But thank you any way for your issue. Let me know if you find something more.
Thanks

**Comment by garzadekoster** [comment]
I have tried and worked  Super.....  Obrigado!!!
